### ISSUE TITLE
Allow XML as FSDB for import.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#154]
If I try to import an `*.fsdb` actually named `*.clean-fsdb.xml` it fails with `405 method not allowed`. Could we do some [content sniffing](https://en.wikipedia.org/wiki/Content_sniffing) to allow `*.xml` with an `<Fs>` root element?

**Comment by kuaka** [comment]
forgive my ignorance but what is the use case here? why would a file be a .xml and not .fsdb?

**Comment by philderbeast** [comment]
We have test files ready to go such as for [2017 Dalby Big Air](https://github.com/FlareTiming/2017-dalby-bigair-score/blob/master/dalby%20open%202017.clean-fsdb.xml). Both these and the `*.fsdb` are XML. Not having to rename the extension is a convenience that will add up if we do a lot of testing.

**Comment by kuaka** [comment]
OK, so I guess you are not calling your files *.fsdb as they have been cleaned of personal info and not virgin exported from FS?

with this change https://github.com/FAI-CIVL/FAI-Airscore/commit/c1770d74b2b29bd78565598cad7611933533b3bf your file above is being imported successfully. 

I have not added any content sniffing or checking yet because I see that there is no checking of the fsdb files.. the process assumes that if it has a .fsdb (and now .xml) extension then it tries to import it and if there are problems the front end hangs. We really need proper error capture and feedback to the front end for both fsdb and xml so working just on the xml seems pointless given that you may be the only user of this and any solution should address both types of file.

**Comment by philderbeast** [comment]
> OK, so I guess you are not calling your files *.fsdb as they have been cleaned of personal info and not virgin exported from FS?

@kuaka, the `*.fsdb` I obtain from scorers. I gitignore these files in curated comp repos so that I don't commit them with the sensitive private data. The `*.clean-fsdb.xml` is cleaned of participant attributes not needed for scoring and the `*.trim-fsdb.xml` has elements and attributes removed that are not used as inputs for scoring by flare-timing. The workings and outputs from FS that I use for making comparisons also remain.
