### ISSUE TITLE
Parse DNF status .

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#225]
Importing from `*.fsdb` please parse DNF status for pilots.

**Comment by philderbeast** [comment]
Those pilots that DNF for task 3, 2018 XC Dalmatian Paragliding Open.

Id | Name
-- | --
21 | Damir Kalinger

**Comment by philderbeast** [comment]
In the [Results] tab for an imported but external event, airScore is showing DNF and ABS status but forgetting this when I convert the comp to airScore and [Bulk Import Tracks]. Please preserve the DNF status after importing tracks, especially if there is no track for a DNF pilot.

**Comment by kuaka** [comment]
in converting a comp all results were being deleted. I have now excluded abs, dnf and mindist from this deletion. 
mindist is debatable as in most cases tracks will exist, however not always. There could be a case where under FS a pilot is awarded mindist but under airScore we might award mindist+X due to differences in distance calc. e.g. if mindist was 5km maybe in airScore a pilot would be awarded 5.01km.
@biuti please review the above commit. I am not that familiar on how this part of airScore works. I have tested with forbes 2018 and it is working but I am not aware if there could be other consequences of not deleting all results. 

@biuti @philderbeast decide if you want mindist in this list of results to keep while converting.

**Comment by biuti** [comment]
> mindist is debatable as in most cases tracks will exist, however not always. There could be a case where under FS a pilot is awarded mindist but under airScore we might award mindist+X due to differences in distance calc. e.g. if mindist was 5km maybe in airScore a pilot would be awarded 5.01km.

Actually `mindist` should be used only for pilots without a valid track. The others will be rewarded mindist points and distance but are `lo`, with a track map.

I will review, but as far as I understood it should be ok, actually I didn't think about it, makes sense to keep results of any pilots without a valid track.

**Comment by kuaka** [comment]
> Actually `mindist` should be used only for pilots without a valid track. The others will be rewarded mindist points and distance but are `lo`, with a track map.

of course! I didn't think of that.
