### ISSUE TITLE
Missing jsonify?

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#235]
All the other `/flaretiming/<compid>/*` URLs `return jsonify(_)` except this one. Was that intentional?

https://github.com/FAI-CIVL/FAI-Airscore/blob/d483e178b854c98ef2f889396a2f19a3b3f64539/airscore/public/views.py#L925

**Comment by kuaka** [comment]
it was intentional. 
What was not intentional was having jsonify on landout and arrival.
It is necessary on route as this is a list. I obviously copied the route code as a template for the others and forgot to remove it. 
It has no effect. 
After a recent update flask will automatically send any dictionary jsonified. Route is a list so it needs to be explicit.

**Comment by kuaka** [comment]
removed redundants with https://github.com/FAI-CIVL/FAI-Airscore/commit/9d7a9f875e1446c2ae99c30ec13ad798ca38d213
