### ISSUE TITLE
bugs in pilot_admin page

### ISSUE THREAD

**Issue by biuti** [FAI-CIVL/FAI-Airscore#87]
- Double clicking pilots in internal list is moving them to registered pilots column but is not adding them and are removed when saving. Either correct or remove double click option.
- edit pilot modal form is not saving correctly all infos in DB.
- add external pilot modal is not saving glider_cert in DB

**Comment by biuti** [comment]
Second point seems to be fixed in Packages branch.

**Comment by kuaka** [comment]
"fixed" or was never broken in packages?

This is working in Dev and I believe that this is the same issue (assuming you are referring to sql refactor branch) as I pointed out with not being able to modify some fields in comp admin and pilot admin with the sql refactor branch.

As an aside this issue needs to be split into 2 issues (one problem per issue so that they can be managed separately)
Also if an issue is not related to master, we should specify what branch it relates to here.

**Comment by biuti** [comment]
No, a field named glider_cert in DB was named 'certification' in form, so it could not be saved / updated.
I changed it in packages branch but looking at dev code it has the same bug.

**Comment by kuaka** [comment]
It is working fine in Dev. I tested earlier. It is not important what it is called in forms, what matters is what it is mapped to in views.py
line 1399 in user/views.py:     participant.glider_cert = data.get('certification')
is the key line. 
(I am referring to edit participant form here, not sure if you are talking about this or add external pilot. This issue should be closed and separate issues opened to avoid confusion)

**Comment by biuti** [comment]
Lines 1427 and 1470.

**Comment by kuaka** [comment]
ok so that is add participant. different issue. will close this.
